/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import dao.PontoDao;
import entidades.Pontos;
import entidades.Funcionarios;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import util.Util;

/**
 *
 * @author carleandro
 */
public class FotoFrame extends javax.swing.JFrame {

    /**
     * Creates new form FotoFrame
     */
    public FotoFrame() {
        initComponents();
    }
    
    public void setIdPonto(int id) throws IOException{
        Object[] object = new PontoDao().getPonto(id);
        Pontos ponto = (Pontos) object[0];
        Funcionarios professor =(Funcionarios) object[1];
        jLabelProfessor.setText(professor.getNome());
        DateFormat format = new SimpleDateFormat("dd/MM/YYYY");
        jLabelData.setText(format.format(ponto.getDatacadastro()));
        jLabelHora.setText(ponto.getHora().toString());
        File dir1 = new File (".");
        String diretorioImagens; 
        diretorioImagens = dir1.getCanonicalPath()+Util.pastaImagem;
        String pathImagem = diretorioImagens+ponto.getImagem();
        File diretorio = new File(pathImagem); 
        ImageIcon imgThisImg;
        if (!diretorio.exists()) {
            imgThisImg = new ImageIcon(dir1.getCanonicalPath()+"/"+"imagempadrao.png");
        }else{
            imgThisImg = new ImageIcon(pathImagem);
        }
        jLabelFoto.setIcon(imgThisImg); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFoto = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelProfessor = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Foto do Ponto");
        setResizable(false);

        jLabelFoto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelFoto.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabelData.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelData.setText("jLabel1");

        jLabelProfessor.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelProfessor.setText("jLabel2");

        jLabelHora.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelHora.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelProfessor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelData)
                                .addGap(162, 162, 162)
                                .addComponent(jLabelHora))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelData)
                    .addComponent(jLabelHora))
                .addGap(10, 10, 10)
                .addComponent(jLabelProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FotoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FotoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FotoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FotoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FotoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelProfessor;
    // End of variables declaration//GEN-END:variables
}
