package entidades;
// Generated 17/03/2019 07:41:02 by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * Auditoria generated by hbm2java
 */
public class Auditoria  implements java.io.Serializable {


     private Integer id;
     private Integer iduser;
     private String nomeuser;
     private Date datacadastro;
     private String texto;

    public Auditoria() {
    }

    public Auditoria(Integer iduser, String nomeuser, String texto, Date datecadastro) {
       this.iduser = iduser;
       this.nomeuser = nomeuser;
       this.texto = texto;
       this.datacadastro = datecadastro;
    }

    public Auditoria(Integer iduser, String nomeuser, Date datacadastro, String texto) {
        this.iduser = iduser;
        this.nomeuser = nomeuser;
        this.datacadastro = datacadastro;
        this.texto = texto;
    }
    

    public Date getDatacadastro() {
        return datacadastro;
    }

    public void setDatacadastro(Date datacadastro) {
        this.datacadastro = datacadastro;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public String getNomeuser() {
        return this.nomeuser;
    }
    
    public void setNomeuser(String nomeuser) {
        this.nomeuser = nomeuser;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }




}


