package entidades;
// Generated 13/03/2019 16:46:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Professors generated by hbm2java
 */
public class Funcionarios  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String cpf;
     private String email;
     private String tipo;
     private String status;
     private Set pontoses = new HashSet(0);
     private Cargos cargos;

    public Funcionarios() {
    }

    public Funcionarios(String nome, String cpf, String email, String tipo, String status, Set pontoses) {
       this.nome = nome;
       this.cpf = cpf;
       this.email = email;
       this.tipo = tipo;
       this.status = status;
       this.pontoses = pontoses;
    }

    public Funcionarios(String nome, String cpf, String email, String tipo, String status, Cargos cargos) {
        this.nome = nome;
        this.cpf = cpf;
        this.email = email;
        this.tipo = tipo;
        this.status = status;
        this.cargos = cargos;
    }
    
    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getPontoses() {
        return this.pontoses;
    }
    
    public void setPontoses(Set pontoses) {
        this.pontoses = pontoses;
    }

    public Cargos getCargos() {
        return cargos;
    }

    public void setCargos(Cargos cargos) {
        this.cargos = cargos;
    }




}


