package entidades;
// Generated 13/03/2019 16:46:12 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pontos generated by hbm2java
 */
public class Pontos  implements java.io.Serializable {


     private Integer id;
     private Funcionarios funcionarios;
     private Date datacadastro;
     private Date hora;
     private String imagem;
     private String tipo;

    public Pontos() {
    }

	
    public Pontos(Funcionarios funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Pontos(Funcionarios funcionarios, Date datacadastro, Date hora, String imagem) {
       this.funcionarios = funcionarios;
       this.datacadastro = datacadastro;
       this.hora = hora;
       this.imagem = imagem;
    }

    public Pontos(Funcionarios funcionarios, Date datacadastro) {
        this.funcionarios = funcionarios;
        this.datacadastro = datacadastro;
    }

    public Pontos(Funcionarios funcionarios, Date datacadastro, Date hora, String imagem, String tipo) {
        this.funcionarios = funcionarios;
        this.datacadastro = datacadastro;
        this.hora = hora;
        this.imagem = imagem;
        this.tipo = tipo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Funcionarios getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Funcionarios funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Date getDatacadastro() {
        return this.datacadastro;
    }
    
    public void setDatacadastro(Date datacadastro) {
        this.datacadastro = datacadastro;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getImagem() {
        return this.imagem;
    }
    
    public void setImagem(String imagem) {
        this.imagem = imagem;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

}


