package entidades;
// Generated 13/03/2019 16:46:12 by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String email;
     private String password;
     private String status;
     private String permissaoroot;

    public Users() {
    }

    public Users(String nome, String email, String password, String status, String permissaoroot) {
       this.nome = nome;
       this.email = email;
       this.password = password;
       this.status = status;
       this.permissaoroot = permissaoroot;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getPermissaoroot() {
        return permissaoroot;
    }

    public void setPermissaoroot(String permissaoroot) {
        this.permissaoroot = permissaoroot;
    }
    
    




}


